# Generated by Django 6.0 on 2025-12-11 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0002_remove_proveedor_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='Código SKU')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('unidad_compra', models.CharField(max_length=30, verbose_name='Unidad de Compra')),
                ('unidad_consumo', models.CharField(max_length=30, verbose_name='Unidad de Consumo/Venta')),
                ('factor_conversion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Factor de Conversión')),
                ('talla', models.CharField(blank=True, max_length=10, null=True, verbose_name='Talla')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Material')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fichas/', verbose_name='Imagen referencial')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('materia_prima', 'Materia Prima / Insumo'), ('producto_terminado', 'Producto Terminado'), ('servicio', 'Servicio')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(default='unidad', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Costo Promedio')),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Precio Base')),
                ('precio_mayorista', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Precio Mayorista')),
                ('precio_distribuidor', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Precio Distribuidor')),
                ('tipo_impuesto', models.CharField(choices=[('iva', 'IVA/IGV'), ('exento', 'Exento')], default='iva', max_length=10, verbose_name='Tipo de Impuesto')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='inventario.familia')),
                ('ficha_tecnica', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo', to='inventario.fichatecnica')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisico', models.PositiveIntegerField(default=0, verbose_name='Stock Físico')),
                ('comprometido', models.PositiveIntegerField(default=0, verbose_name='Stock Comprometido')),
                ('disponible', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('minimo', models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo')),
                ('maximo', models.PositiveIntegerField(default=0, verbose_name='Stock Máximo')),
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventario.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasillo', models.CharField(max_length=10)),
                ('estante', models.CharField(max_length=10)),
                ('nivel', models.CharField(max_length=10)),
                ('caja', models.CharField(blank=True, max_length=10)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='inventario.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(blank=True, max_length=50, verbose_name='Código del Proveedor')),
                ('ultimo_costo', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Último Costo de Compra')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='inventario.articulo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_suministrados', to='proveedores.proveedor')),
            ],
            options={
                'unique_together': {('articulo', 'proveedor')},
            },
        ),
        migrations.CreateModel(
            name='StockUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.almacen')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_ubicacion', to='inventario.articulo')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='inventario.ubicacion')),
            ],
            options={
                'unique_together': {('articulo', 'almacen', 'ubicacion')},
            },
        ),
    ]
