# Generated by Django 6.0 on 2025-12-12 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_autorizacion', 'Pendiente de Autorización'), ('autorizada', 'Autorizada'), ('enviada', 'Enviada/Confirmada'), ('recibida_parcial', 'Recibida Parcial'), ('recibida_total', 'Recibida Total'), ('cancelada', 'Cancelada')], default='borrador', max_length=30),
        ),
        migrations.CreateModel(
            name='AutorizacionOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField()),
                ('autorizado', models.BooleanField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='compras.ordencompra')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_oc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nivel'],
                'unique_together': {('orden', 'nivel')},
            },
        ),
    ]
