# Generated by Django 6.0 on 2025-12-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='categoria',
        ),
    ]
