# Generated by Django 6.0 on 2025-12-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_remove_proveedor_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
    ]
