# Generated by Django 6.0 on 2025-12-12 00:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_delete_ordencompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de alta'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Rating (1-5)'),
        ),
    ]
